"""Shared 32x32 avatar (curly hair, rectangular glasses, headphones) and frame helpers.

Files starting with "_" are not icons; build.py skips them. Edit BASE here and
both avatar_wave and avatar_bob pick up the change on the next build.
"""

BASE = """
    ......KKKKKKKKKKKKKKK...........
    .....KKKKNNNNNNNNNNKKK..........
    ....KKKKNNNKKKKKKNNNKKK.........
    ....KKNNNKKBBBBBBKKNNNKK........
    ....KNNNKbBBbbBBbbBKNNNKK.......
    ...KKNNKbBBBbBBBbBBBKNNKK.......
    ...KNNKbBBbbBBbbBBbbBKNNK.......
    ..KKNKBBBBBBBBBBBBBBBBKNKK......
    ..KNNKbBBBBBBBBBBBBBBBKNNK......
    ..KNKBBBBbBBbbBBbbBBBBBKNK......
    ..KKKKbBBBBBbBBBbBBBBBKKKK......
    .KNNNNKbBBBBBBBBBBBbbKNNNNK.....
    .KNnNNKKKKKKKSSKKKKKKKNnNNK.....
    .KNnNNKKWSSSKKKKWSSSKKNnNNK.....
    .KNnNNKKSKKSKSSKSKKSKKNnNNK.....
    .KNnNNKKSKKSKSSKSKKSKKNnNNK.....
    .KNnNNKKSSSSKSSKSSSSKKNnNNK.....
    .KNnNNKKKKKKKSSKKKKKKKNnNNK.....
    .KNnNNKSPPSSSSSSSSPPsKNnNNK.....
    .KNNNNKSSSSrSssSrSSSsKNNNNK.....
    ..KKKKKSSSSSrrrrSSSSsKKKKK......
    .......KSSSSSSSSSSssK...........
    ........KKSSSSSSSsKK............
    .........KKSSSSSSKK.............
    .....KKKKGgSSSSSSgGKKKK.........
    ....KGGGGGGgSSSSgGGGGGGK........
    ...KGGGGGGGGgSSgGGGGGGGGK.......
    ..KGGGGgGGGGGggGGGGGgGGGGK......
    ..KGGGGgGGGGGGGGGGGGgGGGGK......
    ..KGGGGgGGGGGGGGGGGGgGGGGK......
    ..KGGGGgGGGGGGGGGGGGgGGGGK......
    ..KGGGGgGGGGGGGGGGGGgGGGGK......
    """


def rows(grid):
    return [line.strip() for line in grid.strip("\n").splitlines() if line.strip()]


def stamp(grid, patch, top, left):
    """Copy patch onto grid at (top, left). "." in the patch keeps what's underneath."""
    out = [list(r) for r in rows(grid)]
    for dr, line in enumerate(rows(patch)):
        for dc, ch in enumerate(line):
            if ch != ".":
                out[top + dr][left + dc] = ch
    return "\n".join("".join(r) for r in out)


def shift_head(grid, dy=1, neck_row=23):
    """Move everything above neck_row down by dy; the body stays put."""
    g = rows(grid)
    head, body = g[:neck_row], g[neck_row:]
    moved = ["." * len(g[0])] * dy + head
    top, spill = moved[:neck_row], moved[neck_row:]
    for i, line in enumerate(spill):
        body[i] = "".join(h if h != "." else b for h, b in zip(line, body[i]))
    return "\n".join(top + body)
