"""Developer's Driver: envelope. The flap opens and a letter rises out."""

LABEL = "Developer's Driver"
FPS = 3

FRAMES = [
    # 0: sealed
    """
    ................
    ................
    ................
    ................
    ................
    ................
    .KKKKKKKKKKKKKK.
    .KKWWWWWWWWWWKK.
    .KWKWWWWWWWWKWK.
    .KWWKWWWWWWKWWK.
    .KWWWKWWWWKWWWK.
    .KWWWWKGGKWWWWK.
    .KWWWWWWWWWWWWK.
    .KKKKKKKKKKKKKK.
    ................
    ................
    """,
    # 1: flap opens
    """
    ................
    ................
    .......KK.......
    .....KKLLKK.....
    ...KKLLLLLLKK...
    .KKLLLLLLLLLLKK.
    .KKKKKKKKKKKKKK.
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    .KKWWWWWWWWWWKK.
    .KWKKWWWWWWKKWK.
    .KWWWKKKKKKWWWK.
    .KWWWWWWWWWWWWK.
    .KKKKKKKKKKKKKK.
    ................
    ................
    """,
    # 2: letter peeks out
    """
    ................
    ................
    .......KK.......
    .....KKLLKK.....
    ...KKKKKKKKKK...
    .KKLKWGGGGWKLKK.
    .KKKKWGGGWWKKKK.
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    .KKWWWWWWWWWWKK.
    .KWKKWWWWWWKKWK.
    .KWWWKKKKKKWWWK.
    .KWWWWWWWWWWWWK.
    .KKKKKKKKKKKKKK.
    ................
    ................
    """,
    # 3: letter rises
    """
    ................
    ....KKKKKKKK....
    ....KWWWWWWK....
    ....KWGGGGWK....
    ...KKWWWWWWKK...
    .KKLKWGGGWWKLKK.
    .KKKKWWWWWWKKKK.
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    .KKWWWWWWWWWWKK.
    .KWKKWWWWWWKKWK.
    .KWWWKKKKKKWWWK.
    .KWWWWWWWWWWWWK.
    .KKKKKKKKKKKKKK.
    ................
    ................
    """,
]
