"""MoodLens: magnifying lens over a face that goes from neutral to smiling."""

LABEL = "MoodLens"
FPS = 3

FRAMES = [
    # 0: neutral
    """
    ...KKKK.........
    .KKWYYYKK.......
    .KWYYYYYK.......
    KYYKYYKYYK......
    KYYKYYKYYK......
    KYPYYYYPYK......
    KYYYYYYYYK......
    .KYYKKYYK.......
    .KKYYYYKKK......
    ...KKKKKMMK.....
    ........KMMK....
    .........KMMK...
    ..........KMMK..
    ...........KMMK.
    ............KMMK
    .............KKK
    """,
    # 1: mouth widens
    """
    ...KKKK.........
    .KKWYYYKK.......
    .KWYYYYYK.......
    KYYKYYKYYK......
    KYYKYYKYYK......
    KYPYYYYPYK......
    KYYYYYYYYK......
    .KYKKKKYK.......
    .KKYYYYKKK......
    ...KKKKKMMK.....
    ........KMMK....
    .........KMMK...
    ..........KMMK..
    ...........KMMK.
    ............KMMK
    .............KKK
    """,
    # 2: smile
    """
    ...KKKK.........
    .KKWYYYKK.......
    .KWYYYYYK.......
    KYYKYYKYYK......
    KYYKYYKYYK......
    KYPYYYYPYK......
    KYKYYYYKYK......
    .KYKKKKYK.......
    .KKYYYYKKK......
    ...KKKKKMMK.....
    ........KMMK....
    .........KMMK...
    ..........KMMK..
    ...........KMMK.
    ............KMMK
    .............KKK
    """,
]
