"""Photo Cleaner: photo card swiped off to the left, then the next one drops in."""

LABEL = "Photo Cleaner"
FPS = 4

FRAMES = [
    # 0: photo on screen
    """
    ................
    ................
    ................
    ...KKKKKKKKKK...
    ...KWWWWWWWWK...
    ...KWNNNNYYWK...
    ...KWNNNNYYWK...
    ...KWNNNNNNWK...
    ...KWNggNNNWK...
    ...KWggggggWK...
    ...KWGGGGGGWK...
    ...KWWWWWWWWK...
    ...KKKKKKKKKK...
    ................
    ................
    ................
    """,
    # 1: swiped left
    """
    ................
    ................
    ................
    KKKKKKKKKK......
    KWWWWWWWWK......
    KWNNNNYYWK......
    KWNNNNYYWK.MMM..
    KWNNNNNNWK......
    KWNggNNNWK......
    KWggggggWK.MMM..
    KWGGGGGGWK......
    KWWWWWWWWK......
    KKKKKKKKKK......
    ................
    ................
    ................
    """,
    # 2: almost off screen
    """
    ................
    ................
    ................
    KKK.............
    WWK.............
    YWK.............
    YWK.MMM.........
    NWK.............
    NWK.............
    gWK.MMM.........
    GWK.............
    WWK.............
    KKK.............
    ................
    ................
    ................
    """,
    # 3: next photo drops in
    """
    ...KKKKKKKKKK...
    ...KWWWWWWWWK...
    ...KWNNNNYYWK...
    ...KWNNNNYYWK...
    ...KWNNNNNNWK...
    ...KWNggNNNWK...
    ...KWggggggWK...
    ...KWGGGGGGWK...
    ...KWWWWWWWWK...
    ...KKKKKKKKKK...
    ................
    ................
    ................
    ................
    ................
    ................
    """,
]
