"""MyVoice: speech bubble. Typing dots light up one at a time."""

LABEL = "MyVoice"
FPS = 4

FRAMES = [
    """
    ................
    ................
    ................
    ..KKKKKKKKKKKK..
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    .KWGGWWLLWWLLWK.
    .KWGGWWLLWWLLWK.
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    ..KWWKKKKKKKKK..
    ..KWK...........
    ..KK............
    ................
    ................
    ................
    """,
    """
    ................
    ................
    ................
    ..KKKKKKKKKKKK..
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    .KWLLWWGGWWLLWK.
    .KWLLWWGGWWLLWK.
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    ..KWWKKKKKKKKK..
    ..KWK...........
    ..KK............
    ................
    ................
    ................
    """,
    """
    ................
    ................
    ................
    ..KKKKKKKKKKKK..
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    .KWLLWWLLWWGGWK.
    .KWLLWWLLWWGGWK.
    .KWWWWWWWWWWWWK.
    .KWWWWWWWWWWWWK.
    ..KWWKKKKKKKKK..
    ..KWK...........
    ..KK............
    ................
    ................
    ................
    """,
]
